databases:
  - name: product-feedback-app-api-db
    plan: free

services:
  - type: web
    name: fem-product-feedback-app-api
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: product-feedback-app-api-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
    plan: free
